"""empty message

Revision ID: 4483eb20df32
Revises: 5e77c7cf237f
Create Date: 2019-06-13 15:35:25.346171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4483eb20df32'
down_revision = '5e77c7cf237f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('date_recommended_for', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    # ### end Alembic commands ###
