"""empty message

Revision ID: 5e77c7cf237f
Revises: f551385f39e2
Create Date: 2019-06-08 17:32:24.476575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e77c7cf237f'
down_revision = 'f551385f39e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'checked')
    # ### end Alembic commands ###
